#:schema node_modules/wrangler/config-schema.json
name = "init"
main = "src/index.js"
compatibility_date = "2025-01-09"
rules = [{ type = "Text", globs = ["**/*.sh"], fallthrough = true }]

[observability]
enabled = true

[placement]
mode = "smart"
